### ISSUE TITLE
Instructions for running

### ISSUE THREAD

**Issue by thiagoarrais** [EmmanuelObo/journalize#3]
This seems awesome. Do you mind clarifying how to run it? Some pointers to the relevant python docs would be enough. I'm not a pythonista, so I don't know where to start.

Oh, and thanks for the code!

**Comment by emmanuelobo** [comment]
Hey thanks man. Sorry for the late response, been a bit tied up lately. I actually forgot to put up the the instructions (will get that done soon). But I'll just give you the instructions on how to setup. 

### Setup Virtual Env
In your local machine create a python virtual environment either using virtualenv or pipenv (recommended)

### Clone repo
Clone the repository to your local 
https://github.com/EmmanuelObo/journalize.git

### Activate virtual environment
Wherever your virtual environment was created, there is a Scripts folder inside the main folder. Inside the Scripts folder you will see a Lib folder that contains a script activate.bat.
Run that script inside your terminal from your journalize project location to activate the virtual environment for that project.

### Get All Dependencies
Inside the app folder there will be a file called requirements.txt.
Run the following command:
`pip install -r requirements.txt`

### Run the App
Now you should be all setup and ready to run the app.
To run the app enter the following script:
`python manage.py runserver`
Then navigate to localhost:8080 and the server should be live

Will be adding some more tasks and issues that need to be worked on. But for the time being have fun playing around with it and seeing what can be improved upon.

Thanks!

**Comment by thiagoarrais** [comment]
Thanks! I'll close the issue and get back in touch once I manage to run the code.

How would you prefer to be contacted?

**Comment by emmanuelobo** [comment]
No problem. You can reach me through my email, emmaoobo@gmail.com.
